main:
  build: .
  volumes:
    - .:/code
  links:
    - postgresdb
    - chromedriver
  command: python manage.py scrapy crawl general_course_content
  environment:
    - DEBUG=true


postgresdb:
  build: utils/sql/
  ports:
    - "5432"
  environment:
    - DEBUG=true


chromedriver:
  image: selenium/standalone-chrome
  ports:
    - "4444:4444"
  environment:
    - DEBUG=true
