main:
  build: .
  volumes:
    - .:/code
  environment:
    - DEBUG=true


postgresdb:
  extends:
    file: docker-compose.yml
    service: main
  build: utils/sql/
  ports:
    - "5432"
  environment:
    - DEBUG=true


chromedriver:
  image: selenium/standalone-chrome
  ports:
    - "4444:4444"
  environment:
    - DEBUG=true


scraper:
  command: python scraper/manage.py scrapy crawl general_course_content
  extends:
    file: docker-compose.yml
    service: main
  links:
    - chromedriver
    - postgresdb
  environment:
    - DEBUG=true
