main:
  build: .
  volumes:
    - .:/code
  environment:
    - DEBUG=true
    
chromedriver:
  image: selenium/standalone-chrome
  ports:
    - "4444:4444"
  environment:
    - DEBUG=true

scraper:
  command: python manage.py scrapy crawl general_course_content
  extends:
    file: docker-compose.yml
    service: main
  links:
    - chromedriver
  environment:
    - DEBUG=true
